import itertools
import math
import random
import time
import tracemalloc
from collections import Counter
from functools import lru_cache

try:
    import pulp
except ImportError:  # pragma: no cover - dependency is optional until installed
    pulp = None

try:
    from .rules import RULES, RULE_IDS
except ImportError:
    from rules import RULES, RULE_IDS

# ------------------------------------------------------------
# Core idea of this project:
# - real_passwords.txt  = the universe we want to cover
# - mutated_passwords.txt = targets generated by mutation rules
# - each rule becomes a "coverage set" of real passwords it can match
# - every solver tries to pick k rules that cover as many passwords as possible
# ------------------------------------------------------------

def load_passwords(filenames=("real_passwords.txt", "mutated_passwords.txt")):
    """
    Read real and mutated password lists.
    Empty lines are ignored.
    """
    if isinstance(filenames, str):
        filenames = (filenames, "mutated_passwords.txt")

    real_file = filenames[0] if len(filenames) > 0 else "real_passwords.txt"
    mutated_file = filenames[1] if len(filenames) > 1 else "mutated_passwords.txt"

    data = {"real": [], "mutated": []}
    for key, filename in (("real", real_file), ("mutated", mutated_file)):
        try:
            with open(filename, "r", encoding="utf-8") as f:
                data[key] = [line.strip() for line in f if line.strip()]
        except FileNotFoundError:
            print(f"[!] File '{filename}' not found.")
    return data


def get_universe_passwords(password_data):
    # Accept either a dict {"real": ..., "mutated": ...} or a raw list.
    if isinstance(password_data, dict):
        return password_data.get("real", [])
    return password_data


def get_mutated_passwords(password_data):
    # Mutated passwords are stored as a set because membership checks are frequent.
    if isinstance(password_data, dict):
        return set(password_data.get("mutated", []))
    return set(password_data)


def normalize_candidates(candidates):
    if candidates is None:
        return ()
    if isinstance(candidates, str):
        return (candidates,)
    return tuple(candidates)


def clamp_k(k, rule_count):
    return max(0, min(k, rule_count))


def build_rule_coverages(passwords):
    """
    Build set-based coverage structures.
    rule_coverages[rule_id] = frozenset of password indices covered by that rule.
    password_to_rules[index] = tuple of rule ids covering that password.
    """
    real_passwords = list(get_universe_passwords(passwords))
    mutated_passwords = get_mutated_passwords(passwords)

    rule_coverages = {}
    password_to_rules = {index: [] for index in range(len(real_passwords))}

    for rule_id in RULE_IDS:
        transform = RULES[rule_id]["transform"]
        covered_indices = set()
        for index, password in enumerate(real_passwords):
            # A rule may return one string or many candidate strings.
            candidates = normalize_candidates(transform(password))
            if any(candidate in mutated_passwords for candidate in candidates):
                covered_indices.add(index)
        frozen_coverage = frozenset(covered_indices)
        rule_coverages[rule_id] = frozen_coverage
        for index in frozen_coverage:
            password_to_rules[index].append(rule_id)

    for index in password_to_rules:
        password_to_rules[index].sort()

    return rule_coverages, password_to_rules, real_passwords


def coverage_of_rules(rule_coverages, selected_rule_ids):
    # Union all coverage sets of the selected rules.
    covered = set()
    for rule_id in selected_rule_ids:
        covered.update(rule_coverages[rule_id])
    return covered


def coverage_counts(rule_coverages, selected_rule_ids):
    # Count how many selected rules cover each password index.
    # This is useful for swap-based local search.
    counts = Counter()
    for rule_id in selected_rule_ids:
        counts.update(rule_coverages[rule_id])
    return counts


def covered_passwords_from_indices(real_passwords, covered_indices):
    return [real_passwords[index] for index in sorted(covered_indices)]


def rule_names(rule_ids):
    return [f"[{rule_id}] {RULES[rule_id]['label']}" for rule_id in rule_ids]


<<<<<<< HEAD
def result_payload(method_name, k, selected_rule_ids, passwords, covered_indices):
    # Normalize everything into a single return object so every solver
    # produces the same output format.
    real_passwords = get_universe_passwords(passwords)
    covered_passwords = covered_passwords_from_indices(real_passwords, covered_indices)
    total_passwords = len(real_passwords)
    mutated_count = len(passwords.get("mutated", [])) if isinstance(passwords, dict) else 0
    covered_set = frozenset(covered_indices)
=======
def result_payload(method_name, k, selected_rule_ids, passwords, covered_mask):
    covered_passwords = mask_to_passwords(passwords, covered_mask)
    total_passwords = len(get_universe_passwords(passwords))
    mutated_count = len(passwords.get("mutated", [])) if isinstance(passwords, dict) else 0
>>>>>>> 30a8b8fd0e6fbf6277d0085b7730970b7b55067c
    return {
        "method": method_name,
        "k": k,
        "selected_rule_ids": selected_rule_ids,
        "selected_rules": rule_names(selected_rule_ids),
        "covered_mask": covered_set,
        "covered_indices": covered_set,
        "covered_passwords": covered_passwords,
        "coverage_count": len(covered_set),
        "total_passwords": total_passwords,
        "mutated_passwords": mutated_count,
    }


def save_answer(filename, result):
    """
    Write the result file.
    """
    with open(filename, "w", encoding="utf-8") as f:
        f.write("Method:\n")
        f.write(f"{result['method']}\n")

        f.write("\nFixed number of selected rules (k):\n")
        f.write(f"{result['k']}\n")

        f.write("\nInput summary:\n")
        f.write(f"Real passwords: {result['total_passwords']}\n")
        f.write(f"Mutated passwords: {result['mutated_passwords']}\n")

        f.write("\nSelected rules:\n")
        if result["selected_rules"]:
            for rule in result["selected_rules"]:
                f.write(f"{rule}\n")
        else:
            f.write("null\n")

        f.write("\nCovered passwords:\n")
        if result["covered_passwords"]:
            for password in result["covered_passwords"]:
                f.write(f"{password}\n")
        else:
            f.write("null\n")

        f.write("\nCoverage:\n")
        f.write(f"{result['coverage_count']} / {result['total_passwords']}\n")

    print(f"[+] Results saved to: {filename}")


def run_solver(method_name, solver, k, passwords, output_prefix):
    """
    Run a solver, measure time and memory, then save the result.
    """
    # The solver itself only returns the answer.
    # This helper handles timing, memory measurement, printing, and output files.
    tracemalloc.start()
    start_time = time.perf_counter()

    result = solver(passwords, k)

    end_time = time.perf_counter()
    current_memory, peak_memory = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    output_file = f"{output_prefix}_k{k}.txt"
    save_answer(output_file, result)

    print(f"\n============= {method_name.upper()} =============")
    print("[+] Selected Rules :")
    if result["selected_rules"]:
        for rule in result["selected_rules"]:
            print(f"    {rule}")
    else:
        print("    null")
    print(f"[+] Covered        : {result['coverage_count']}/{result['total_passwords']}")
    print(f"[+] Execution Time : {end_time - start_time:.6f} s")
    print(f"[+] Memory Used    : {current_memory / 1024:.2f} KB | {current_memory / (1024 * 1024):.4f} MB")
    print(f"[+] Peak Memory    : {peak_memory / 1024:.2f} KB | {peak_memory / (1024 * 1024):.4f} MB")
    print("==============================================")
    return result


def gain_of_rule(rule_coverages, covered_indices, rule_id):
    # How many NEW passwords would this rule add?
    return len(rule_coverages[rule_id] - covered_indices)


def best_rule_by_gain(rule_coverages, covered_indices, candidate_rule_ids):
    # Used by greedy-style filling: pick the rule with the largest marginal gain.
    best_rule_id = None
    best_coverage = frozenset(covered_indices)
    best_gain = -1
    for rule_id in candidate_rule_ids:
        candidate_coverage = covered_indices | rule_coverages[rule_id]
        gain = len(candidate_coverage) - len(covered_indices)
        if gain > best_gain:
            best_gain = gain
            best_rule_id = rule_id
            best_coverage = candidate_coverage
    return best_rule_id, best_coverage, best_gain


def random_selection(rule_ids, k, rng):
    # Randomly sample exactly k rules, keeping the result sorted for stable output.
    if k <= 0:
        return []
    if k >= len(rule_ids):
        return list(rule_ids)
    return sorted(rng.sample(rule_ids, k))


def complete_to_k(rule_coverages, selected_rule_ids, rule_ids, target_k):
    # If we currently selected fewer than k rules, keep adding the best
    # remaining rule until we reach k.
    selected = list(selected_rule_ids)
    selected_set = set(selected)
    covered_indices = coverage_of_rules(rule_coverages, selected)
    remaining = [rule_id for rule_id in rule_ids if rule_id not in selected_set]

    while len(selected) < target_k and remaining:
        best_rule_id, best_coverage, _ = best_rule_by_gain(rule_coverages, covered_indices, remaining)
        if best_rule_id is None:
            break
        selected.append(best_rule_id)
        selected_set.add(best_rule_id)
        covered_indices = best_coverage
        remaining.remove(best_rule_id)

    return selected, covered_indices


def trim_to_k(rule_coverages, selected_rule_ids, target_k):
    # If we selected too many rules, remove the one that hurts coverage least.
    selected = list(selected_rule_ids)
    if len(selected) <= target_k:
        return selected, coverage_of_rules(rule_coverages, selected)

    while len(selected) > target_k:
        current_coverage = coverage_of_rules(rule_coverages, selected)
        worst_index = None
        worst_loss = None

        for index, rule_id in enumerate(selected):
            reduced_selected = selected[:index] + selected[index + 1 :]
            reduced_coverage = coverage_of_rules(rule_coverages, reduced_selected)
            loss = len(current_coverage) - len(reduced_coverage)
            if worst_loss is None or loss < worst_loss:
                worst_loss = loss
                worst_index = index

        if worst_index is None:
            break
        selected.pop(worst_index)

    return selected, coverage_of_rules(rule_coverages, selected)


def apply_swap_to_state(current_counts, current_covered, removed_cover, added_cover):
    # Update coverage counters after a 1-swap move.
    for index in removed_cover:
        count = current_counts[index] - 1
        if count <= 0:
            current_counts.pop(index, None)
            current_covered.discard(index)
        else:
            current_counts[index] = count

    for index in added_cover:
        current_counts[index] += 1
        current_covered.add(index)


def swap_gain(current_counts, current_covered, removed_cover, added_cover):
    # Estimate the net gain of replacing one selected rule with another.
    # Positive value means the swap is worth trying.
    added = sum(1 for index in added_cover if index not in current_covered)
    lost = sum(1 for index in removed_cover if current_counts[index] == 1 and index not in added_cover)
    return added - lost


def solve_bruteforce(passwords, k):
    """
    Exact search by trying every combination of exactly k rules.
    """
    # This is the baseline exact method.
    # It is simple but becomes expensive very quickly because it enumerates combinations.
    rule_coverages, _, real_passwords = build_rule_coverages(passwords)
    rule_ids = list(RULE_IDS)
    k = clamp_k(k, len(rule_ids))

    if k == 0 or not real_passwords:
        return result_payload("brute force", k, [], passwords, frozenset())

    best_rule_ids = []
    best_coverage = frozenset()
    best_count = -1

    for combo in itertools.combinations(rule_ids, k):
        coverage = coverage_of_rules(rule_coverages, combo)
        count = len(coverage)
        if count > best_count:
            best_count = count
            best_coverage = frozenset(coverage)
            best_rule_ids = list(combo)

    return result_payload("brute force", k, best_rule_ids, passwords, best_coverage)


def solve_greedy(passwords, k):
    """
    Greedy: choose the rule that adds the largest new coverage at each step.
    """
    # Start from an empty solution and keep adding the best rule at each iteration.
    rule_coverages, _, real_passwords = build_rule_coverages(passwords)
    remaining_rule_ids = list(RULE_IDS)
    selected_rule_ids = []
    covered_indices = set()
    k = clamp_k(k, len(RULE_IDS))

    while len(selected_rule_ids) < k and remaining_rule_ids:
        best_rule_id = None
        best_coverage = frozenset(covered_indices)
        best_gain = -1

        for rule_id in remaining_rule_ids:
            candidate_coverage = covered_indices | rule_coverages[rule_id]
            gain = len(candidate_coverage) - len(covered_indices)
            if gain > best_gain:
                best_gain = gain
                best_rule_id = rule_id
                best_coverage = candidate_coverage

        if best_rule_id is None:
            break

        selected_rule_ids.append(best_rule_id)
        remaining_rule_ids.remove(best_rule_id)
        covered_indices = set(best_coverage)

    return result_payload("greedy", k, selected_rule_ids, passwords, covered_indices)


def solve_randomized_search(passwords, k, iterations=None, seed=None):
    """
    Randomized search: sample many feasible k-rule subsets and keep the best one.
    """
    # Heuristic idea:
    # try many random subsets, but initialize the best answer with a greedy solution.
    rule_coverages, _, real_passwords = build_rule_coverages(passwords)
    rule_ids = list(RULE_IDS)
    k = clamp_k(k, len(rule_ids))

    if k == 0 or not real_passwords:
        return result_payload("randomized search", k, [], passwords, frozenset())

    if iterations is None:
        iterations = max(40, len(rule_ids) * max(1, k) * 2)

    base_seed = seed if seed is not None else (len(rule_ids) * 1009 + k * 97 + len(real_passwords))
    rng = random.Random(base_seed)

    greedy_result = solve_greedy(passwords, k)
    best_rule_ids = list(greedy_result["selected_rule_ids"])
    best_coverage = frozenset(greedy_result["covered_indices"])
    best_count = len(best_coverage)

    for _ in range(iterations):
        candidate_rule_ids = random_selection(rule_ids, k, rng)
        candidate_coverage = coverage_of_rules(rule_coverages, candidate_rule_ids)
        candidate_count = len(candidate_coverage)
        if candidate_count > best_count:
            best_rule_ids = list(candidate_rule_ids)
            best_coverage = frozenset(candidate_coverage)
            best_count = candidate_count

    return result_payload("randomized search", k, best_rule_ids, passwords, best_coverage)


def solve_local_search(passwords, k):
    """
    Basic local search with first-improvement swaps from a random starting point.
    """
    # Local search = start with one valid solution, then try to improve it by
    # swapping one chosen rule with one unchosen rule.
    rule_coverages, _, real_passwords = build_rule_coverages(passwords)
    rule_ids = list(RULE_IDS)
    k = clamp_k(k, len(rule_ids))

    if k == 0 or not real_passwords:
        return result_payload("local search", k, [], passwords, frozenset())

    rng = random.Random(len(rule_ids) * 2003 + k * 131 + len(real_passwords))
    current_rule_ids = random_selection(rule_ids, k, rng)
    current_counts = coverage_counts(rule_coverages, current_rule_ids)
    current_covered = set(current_counts.keys())

    improved = True
    while improved:
        improved = False
        current_score = len(current_covered)
        selected_set = set(current_rule_ids)
        remaining_rule_ids = [rule_id for rule_id in rule_ids if rule_id not in selected_set]
        rng.shuffle(remaining_rule_ids)

        for remove_index, removed_rule in enumerate(list(current_rule_ids)):
            removed_cover = rule_coverages[removed_rule]
            for added_rule in remaining_rule_ids:
                added_cover = rule_coverages[added_rule]
                gain = swap_gain(current_counts, current_covered, removed_cover, added_cover)
                if gain > 0:
                    current_rule_ids[remove_index] = added_rule
                    current_counts = coverage_counts(rule_coverages, current_rule_ids)
                    current_covered = set(current_counts.keys())
                    improved = True
                    break
            if improved:
                break

    current_rule_ids = sorted(current_rule_ids)
    return result_payload("local search", k, current_rule_ids, passwords, current_covered)


def solve_hill_climbing(passwords, k):
    """
    Hill climbing with best-improvement 1-swap moves from a greedy starting point.
    """
    # Hill climbing is like local search, but it starts from a greedy solution
    # and keeps the best improving swap in each round.
    rule_coverages, _, real_passwords = build_rule_coverages(passwords)
    rule_ids = list(RULE_IDS)
    k = clamp_k(k, len(rule_ids))

    if k == 0 or not real_passwords:
        return result_payload("hill climbing", k, [], passwords, frozenset())

    current_rule_ids = solve_greedy(passwords, k)["selected_rule_ids"]
    current_rule_ids = sorted(current_rule_ids)
    current_counts = coverage_counts(rule_coverages, current_rule_ids)
    current_covered = set(current_counts.keys())

    improved = True
    while improved:
        improved = False
        current_score = len(current_covered)
        best_rule_ids = list(current_rule_ids)
        best_counts = current_counts
        best_covered = set(current_covered)
        selected_set = set(current_rule_ids)
        remaining_rule_ids = [rule_id for rule_id in rule_ids if rule_id not in selected_set]

        for remove_index, removed_rule in enumerate(current_rule_ids):
            removed_cover = rule_coverages[removed_rule]
            for added_rule in remaining_rule_ids:
                added_cover = rule_coverages[added_rule]
                gain = swap_gain(current_counts, current_covered, removed_cover, added_cover)
                if gain > 0:
                    candidate_rule_ids = list(current_rule_ids)
                    candidate_rule_ids[remove_index] = added_rule
                    candidate_counts = coverage_counts(rule_coverages, candidate_rule_ids)
                    candidate_covered = set(candidate_counts.keys())
                    if len(candidate_covered) > current_score and len(candidate_covered) > len(best_covered):
                        best_rule_ids = sorted(candidate_rule_ids)
                        best_counts = candidate_counts
                        best_covered = candidate_covered
                        improved = True

        current_rule_ids = best_rule_ids
        current_counts = best_counts
        current_covered = best_covered

    return result_payload("hill climbing", k, current_rule_ids, passwords, current_covered)


def solve_beam_search(passwords, k, beam_width=None):
    """
    Beam search over partial rule selections.
    """
    # Beam search keeps only a small set of the best partial solutions.
    # This explores more than greedy, but still avoids full brute force.
    rule_coverages, _, real_passwords = build_rule_coverages(passwords)
    rule_ids = list(RULE_IDS)
    rule_position = {rule_id: index for index, rule_id in enumerate(rule_ids)}
    k = clamp_k(k, len(rule_ids))

    if k == 0 or not real_passwords:
        return result_payload("beam search", k, [], passwords, frozenset())

    if beam_width is None:
        beam_width = max(3, min(8, len(rule_ids)))

    beam = [((), frozenset())]
    for depth in range(k):
        next_states = []
        for selected_rule_ids, covered_indices in beam:
            start_index = 0
            if selected_rule_ids:
                start_index = rule_position[selected_rule_ids[-1]] + 1

            remaining_slots = k - depth - 1
            upper_bound = len(rule_ids) - remaining_slots
            for index in range(start_index, upper_bound):
                rule_id = rule_ids[index]
                new_selected_rule_ids = selected_rule_ids + (rule_id,)
                new_covered_indices = covered_indices | rule_coverages[rule_id]
                next_states.append((new_selected_rule_ids, frozenset(new_covered_indices)))

        if not next_states:
            break

        next_states.sort(
            key=lambda item: (len(item[1]), len(item[0]), item[0]),
            reverse=True,
        )
        beam = next_states[:beam_width]

    best_selected_rule_ids, best_covered_indices = max(
        beam,
        key=lambda item: (len(item[1]), len(item[0]), item[0]),
    )
    return result_payload("beam search", k, list(best_selected_rule_ids), passwords, best_covered_indices)


def solve_dp(passwords, k):
    """
    Exact search with memoization.
    This is practical for small instances because the state space grows fast.
    """
    # DP here stores states based on:
    # - which rule index we are allowed to use next
    # - how many rules we still need
    # - which passwords are already covered
    rule_coverages, _, real_passwords = build_rule_coverages(passwords)
    rule_ids = list(RULE_IDS)
    k = clamp_k(k, len(rule_ids))

    if k == 0 or not real_passwords:
        return result_payload("dynamic programming", k, [], passwords, frozenset())

    @lru_cache(maxsize=None)
    def best_solution(start_index, remaining, covered_state):
        covered_indices = set(covered_state)
        if remaining == 0:
            return len(covered_indices), ()

        best_count = len(covered_indices)
        best_selected = ()
        last_start = len(rule_ids) - remaining + 1

        for index in range(start_index, last_start):
            rule_id = rule_ids[index]
            next_covered = frozenset(covered_indices | rule_coverages[rule_id])
            candidate_count, rest_selected = best_solution(index + 1, remaining - 1, next_covered)
            if candidate_count > best_count or not best_selected:
                best_count = candidate_count
                best_selected = (rule_id,) + rest_selected

        return best_count, best_selected

    _, selected_rules = best_solution(0, k, frozenset())
    covered_indices = coverage_of_rules(rule_coverages, selected_rules)
    return result_payload("dynamic programming", k, list(selected_rules), passwords, covered_indices)


def solve_ilp_pulp_cbc(passwords, k):
    """
    Exact 0-1 Integer Linear Programming model for Maximum Coverage.
    """
    # ILP turns the problem into binary decision variables:
    # x_i = choose rule i or not
    # y_j = password j covered or not
    if pulp is None:
        raise RuntimeError(
            "PuLP is required for ILP_PuLP_CBC. Install it with `pip install pulp`."
        )

    rule_coverages, password_to_rules, real_passwords = build_rule_coverages(passwords)
    rule_ids = list(RULE_IDS)
    k = clamp_k(k, len(rule_ids))

    if k == 0 or not real_passwords:
        return result_payload("ILP + PuLP + CBC", k, [], passwords, frozenset())

    problem = pulp.LpProblem("MaximumCoverage", pulp.LpMaximize)
    x_vars = {
        rule_id: pulp.LpVariable(f"x_{rule_id}", cat=pulp.LpBinary)
        for rule_id in rule_ids
    }
    y_vars = {
        index: pulp.LpVariable(f"y_{index}", cat=pulp.LpBinary)
        for index in range(len(real_passwords))
    }

    problem += pulp.lpSum(y_vars[index] for index in range(len(real_passwords)))
    problem += pulp.lpSum(x_vars[rule_id] for rule_id in rule_ids) == k

    for index, covering_rule_ids in password_to_rules.items():
        if covering_rule_ids:
            problem += y_vars[index] <= pulp.lpSum(x_vars[rule_id] for rule_id in covering_rule_ids)
        else:
            problem += y_vars[index] == 0

    solver = pulp.PULP_CBC_CMD(msg=False)
    status = problem.solve(solver)
    if pulp.LpStatus[status] != "Optimal":
        raise RuntimeError(
            f"CBC did not find an optimal solution. Status: {pulp.LpStatus[status]}"
        )

    selected_rule_ids = [
        rule_id
        for rule_id in rule_ids
        if pulp.value(x_vars[rule_id]) and pulp.value(x_vars[rule_id]) > 0.5
    ]

    covered_indices = coverage_of_rules(rule_coverages, selected_rule_ids)
    return result_payload(
        "ILP + PuLP + CBC",
        k,
        selected_rule_ids,
        passwords,
        covered_indices,
    )


def solve_lagrangian_relaxation(passwords, k, iterations=None):
    """
<<<<<<< HEAD
    Lagrangian relaxation with a simple subgradient-style penalty update.
    This is a practical heuristic for the project.
=======
    Exact search co memoization.
    Trang thai phai gom ca covered_mask vi gia tri cua rule tiep theo
    phu thuoc vao cac password da duoc cover truoc do.
>>>>>>> 30a8b8fd0e6fbf6277d0085b7730970b7b55067c
    """
    # We relax the "choose exactly k rules" constraint by adding a penalty term.
    # Then we repeatedly update the penalty to move the solution closer to k.
    rule_coverages, _, real_passwords = build_rule_coverages(passwords)
    rule_ids = list(RULE_IDS)
    k = clamp_k(k, len(rule_ids))

    if k == 0 or not real_passwords:
        return result_payload("lagrangian relaxation", k, [], passwords, frozenset())

<<<<<<< HEAD
    if iterations is None:
        iterations = max(12, len(rule_ids) * 2)

    best_rule_ids = []
    best_coverage = frozenset()
    best_count = -1

    lambda_penalty = 0.0
    step = max(0.5, math.sqrt(len(rule_ids)) / max(1, k))

    for _ in range(iterations):
        selected_rule_ids = []
        remaining_rule_ids = list(rule_ids)
        covered_indices = set()

        while remaining_rule_ids:
            # Try each remaining rule and keep the one with the best adjusted gain.
            best_rule_id = None
            best_adjusted_gain = float("-inf")
            best_gain = -1
            best_candidate_coverage = frozenset(covered_indices)

            for rule_id in remaining_rule_ids:
                candidate_coverage = covered_indices | rule_coverages[rule_id]
                gain = len(candidate_coverage) - len(covered_indices)
                adjusted_gain = gain - lambda_penalty
                if adjusted_gain > best_adjusted_gain or (
                    adjusted_gain == best_adjusted_gain and gain > best_gain
                ):
                    best_adjusted_gain = adjusted_gain
                    best_gain = gain
                    best_rule_id = rule_id
                    best_candidate_coverage = candidate_coverage

            if best_rule_id is None or best_adjusted_gain <= 0:
                break

            selected_rule_ids.append(best_rule_id)
            remaining_rule_ids.remove(best_rule_id)
            covered_indices = set(best_candidate_coverage)

        relaxed_count = len(selected_rule_ids)
        # If we selected too many rules, increase the penalty.
        # If we selected too few, decrease it.
        lambda_penalty = max(0.0, lambda_penalty + step * (relaxed_count - k))

        feasible_rule_ids = list(selected_rule_ids)
        feasible_coverage = frozenset(covered_indices)
        if len(feasible_rule_ids) < k:
            feasible_rule_ids, feasible_coverage = complete_to_k(
                rule_coverages,
                feasible_rule_ids,
                rule_ids,
                k,
            )
        elif len(feasible_rule_ids) > k:
            feasible_rule_ids, feasible_coverage = trim_to_k(rule_coverages, feasible_rule_ids, k)
        else:
            feasible_coverage = frozenset(covered_indices)

        feasible_count = len(feasible_coverage)
        if feasible_count > best_count:
            best_rule_ids = list(feasible_rule_ids)
            best_coverage = frozenset(feasible_coverage)
            best_count = feasible_count

    if len(best_rule_ids) < k:
        best_rule_ids, best_coverage = complete_to_k(rule_coverages, best_rule_ids, rule_ids, k)

    return result_payload(
        "lagrangian relaxation",
        k,
        sorted(best_rule_ids),
        passwords,
        best_coverage,
    )
=======
    @lru_cache(maxsize=None)
    def best_solution(start_index, remaining, covered_mask):
        if remaining == 0:
            return covered_mask, ()

        best_mask = covered_mask
        best_selected = ()
        last_start = len(rule_ids) - remaining + 1
        for index in range(start_index, last_start):
            rule_id = rule_ids[index]
            next_mask = covered_mask | rule_masks[rule_id]
            candidate_mask, rest_selected = best_solution(index + 1, remaining - 1, next_mask)
            if candidate_mask.bit_count() > best_mask.bit_count() or not best_selected:
                best_mask = candidate_mask
                best_selected = (rule_id,) + rest_selected
        return best_mask, best_selected

    covered_mask, selected_rules = best_solution(0, k, 0)
    return result_payload("dynamic programming", k, list(selected_rules), passwords, covered_mask)
>>>>>>> 30a8b8fd0e6fbf6277d0085b7730970b7b55067c
